import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';

class PdfService {

  static Future<String> generateCalibrationPDF(CalibrationReport report) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: pw.EdgeInsets.all(20),
        build: (pw.Context ctx) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text("Calibration Report",
                  style: pw.TextStyle(
                    fontSize: 28,
                    fontWeight: pw.FontWeight.bold,
                  )),
              pw.SizedBox(height: 20),

              pw.Text("Date: ${report.date}"),
              pw.SizedBox(height: 10),

              pw.Text("Lot Mark: ${report.lotMark}"),
              pw.SizedBox(height: 10),

              pw.Text("Origin: ${report.origin}"),
              pw.SizedBox(height: 10),

              pw.Text("Weight Per Bag: ${report.perBagWeight}"),
              pw.SizedBox(height: 20),

              pw.Divider(),

              pw.Text("Additional Fields",
                  style: pw.TextStyle(
                    fontSize: 18,
                    fontWeight: pw.FontWeight.bold,
                  )),
              pw.SizedBox(height: 15),

              pw.Text("Moisture: ${report.moisture ?? 'N/A'}"),
              pw.Text("Outturn: ${report.outturn ?? 'N/A'}"),
              pw.Text("Remarks: ${report.remarks ?? 'N/A'}"),

              pw.SizedBox(height: 30),
              pw.Text("Generated by FictileCore Factory App",
                  style: pw.TextStyle(fontSize: 12)),
            ],
          );
        },
      ),
    );

    final directory = await getApplicationDocumentsDirectory();
    final filePath = "${directory.path}/Calibration_Report_${report.id}.pdf";

    final file = File(filePath);
    await file.writeAsBytes(await pdf.save());

    return filePath;
  }
}



class CalibrationReport {
  final int id;
  final DateTime date;
  final String lotMark;
  final String origin;
  final double perBagWeight;
  final double? moisture;
  final double? outturn;
  final String? remarks;

  CalibrationReport({
    required this.id,
    required this.date,
    required this.lotMark,
    required this.origin,
    required this.perBagWeight,
    this.moisture,
    this.outturn,
    this.remarks,
  });
}

